# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/ariccegho/git/PythonProjects/test3.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(690, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.connectButton = QtWidgets.QPushButton(self.centralwidget)
        self.connectButton.setGeometry(QtCore.QRect(10, 70, 121, 25))
        self.connectButton.setObjectName("connectButton")
        self.hostLine = QtWidgets.QLineEdit(self.centralwidget)
        self.hostLine.setGeometry(QtCore.QRect(10, 40, 191, 25))
        self.hostLine.setObjectName("hostLine")
        self.unLine = QtWidgets.QLineEdit(self.centralwidget)
        self.unLine.setGeometry(QtCore.QRect(450, 40, 113, 25))
        self.unLine.setObjectName("unLine")
        self.portLine = QtWidgets.QLineEdit(self.centralwidget)
        self.portLine.setGeometry(QtCore.QRect(220, 40, 81, 25))
        self.portLine.setObjectName("portLine")
        self.dbnLine = QtWidgets.QLineEdit(self.centralwidget)
        self.dbnLine.setGeometry(QtCore.QRect(320, 40, 113, 25))
        self.dbnLine.setObjectName("dbnLine")
        self.passLine = QtWidgets.QLineEdit(self.centralwidget)
        self.passLine.setGeometry(QtCore.QRect(570, 40, 113, 25))
        self.passLine.setObjectName("passLine")
        self.hostLabel = QtWidgets.QLabel(self.centralwidget)
        self.hostLabel.setGeometry(QtCore.QRect(20, 10, 67, 17))
        self.hostLabel.setObjectName("hostLabel")
        self.portLabel = QtWidgets.QLabel(self.centralwidget)
        self.portLabel.setGeometry(QtCore.QRect(220, 10, 67, 17))
        self.portLabel.setObjectName("portLabel")
        self.dbnLabel = QtWidgets.QLabel(self.centralwidget)
        self.dbnLabel.setGeometry(QtCore.QRect(330, 10, 67, 17))
        self.dbnLabel.setObjectName("dbnLabel")
        self.unLabel = QtWidgets.QLabel(self.centralwidget)
        self.unLabel.setGeometry(QtCore.QRect(450, 10, 81, 17))
        self.unLabel.setObjectName("unLabel")
        self.passLabel = QtWidgets.QLabel(self.centralwidget)
        self.passLabel.setGeometry(QtCore.QRect(570, 10, 67, 17))
        self.passLabel.setObjectName("passLabel")
        self.save_setButton = QtWidgets.QPushButton(self.centralwidget)
        self.save_setButton.setGeometry(QtCore.QRect(140, 70, 171, 25))
        self.save_setButton.setObjectName("save_setButton")
        self.load_setButton = QtWidgets.QPushButton(self.centralwidget)
        self.load_setButton.setGeometry(QtCore.QRect(320, 70, 171, 25))
        self.load_setButton.setObjectName("load_setButton")
        self.ofButton = QtWidgets.QPushButton(self.centralwidget)
        self.ofButton.setGeometry(QtCore.QRect(10, 190, 221, 25))
        self.ofButton.setObjectName("ofButton")
        self.status_listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.status_listWidget.setGeometry(QtCore.QRect(10, 120, 671, 61))
        self.status_listWidget.setObjectName("status_listWidget")
        self.status_label = QtWidgets.QLabel(self.centralwidget)
        self.status_label.setGeometry(QtCore.QRect(10, 100, 67, 17))
        self.status_label.setObjectName("status_label")
        self.del_spButton = QtWidgets.QPushButton(self.centralwidget)
        self.del_spButton.setGeometry(QtCore.QRect(10, 220, 221, 25))
        self.del_spButton.setObjectName("del_spButton")
        self.save_excelButton = QtWidgets.QPushButton(self.centralwidget)
        self.save_excelButton.setGeometry(QtCore.QRect(10, 250, 221, 25))
        self.save_excelButton.setObjectName("save_excelButton")
        self.load_dataButton = QtWidgets.QPushButton(self.centralwidget)
        self.load_dataButton.setGeometry(QtCore.QRect(240, 190, 201, 25))
        self.load_dataButton.setObjectName("load_dataButton")
        self.load_table_settingsButton = QtWidgets.QPushButton(self.centralwidget)
        self.load_table_settingsButton.setGeometry(QtCore.QRect(240, 220, 201, 25))
        self.load_table_settingsButton.setObjectName("load_table_settingsButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Excel To PSQL"))
        self.connectButton.setText(_translate("MainWindow", "Подключиться"))
        self.hostLabel.setText(_translate("MainWindow", "Host IP"))
        self.portLabel.setText(_translate("MainWindow", "Host Port"))
        self.dbnLabel.setText(_translate("MainWindow", "DB Name"))
        self.unLabel.setText(_translate("MainWindow", "Username"))
        self.passLabel.setText(_translate("MainWindow", "Password"))
        self.save_setButton.setText(_translate("MainWindow", "Сохранить настройки"))
        self.load_setButton.setText(_translate("MainWindow", "Загрузить настройки"))
        self.ofButton.setText(_translate("MainWindow", "Открыть файл"))
        self.status_label.setText(_translate("MainWindow", "Статус:"))
        self.del_spButton.setText(_translate("MainWindow", "Удалить строки с пробелами"))
        self.save_excelButton.setText(_translate("MainWindow", "Сохранить файл"))
        self.load_dataButton.setText(_translate("MainWindow", "Загрузить данные"))
        self.load_table_settingsButton.setText(_translate("MainWindow", "Загрузить данные таблиц"))
